### ISSUE TITLE
Add support for Args to own values.

### ISSUE THREAD

**Issue by halzy** [museun/markings#17]
When using the `Template::find_keys()` function, named arguments can be added if they are needed. 

To keep from calculating expensive arguments, it would be convenient to be able to support:
```
let mut keys: HashSet<&str> = Template::find_keys(&template_string).map(|keys| keys.into_iter().collect())?;

let mut variables = Args::new();
if keys.remove("name") {
    // This could be very expensive to calculate
    let name = message.display_name().unwrap_or_else(|| &message.name);
    variables = variables.with("name", &name);
}
```

Avoiding expensive and unneeded DB calls would be very useful.

**Comment by museun** [comment]
I redid the Args, it'll always take ownership (via an allocation) of the values, but the keys can be either borrowed or owned. The lifetime of the args is for the key: `'static` if its a `String`.

```rust
// owned
let args : Args<'static> = Arg::new().with("foo".to_string(), &42);
// borrowed
let key = "foo".to_string(); 
let args : Args = Arg::new().with(&"foo", &42); // inferred to be the lifetime of the key borrow
```
